name: Run checks

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

# Cancel previous runs if the PR is updated before completion.
concurrency:
  group: ${{ github.ref }}-check
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install linux packages
      run: ./setup-linters.sh
    - name: check shell scripts
      run: shellcheck setup-env.sh install-cmake.sh install-valgrind.sh
    - name: script permissions
      run: chmod +x ./setup-env.sh ./install-cmake.sh ./install-valgrind.sh
    - name: lint code
      run: clang-format-20 --dry-run --Werror -style=file:.clang-format src/**.cpp include/stochastic_models/**/**.h tests/**.cpp
    - name: Install dependencies
      run: ./setup-env.sh
    - name: Install cmake
      run: ./install-cmake.sh
    - name: Install valgrind
      run: ./install-valgrind.sh
    - name: Create build files
      run: cmake .
    - name: Build application
      run: cmake --build . --target install
    - name: Run tests
      run: ./tests/unit_tests
    - name: Run valgrind
      run: valgrind -s --error-exitcode=1 --tool=memcheck --leak-check=full ./tests/unit_tests

